package state_graph

import (
	"context"
	"errors"
	"fmt"
)

type StateGraph struct {
    nodes map[string]Node
    edges []Edge
    entryPoint string
    state *State
}

type State struct {
    data map[string]interface{}
}

// TypedDict - интерфейс для TypedDict
type TypedDict interface {
    Get(key string) interface{}
    Set(key string, value interface{})
}

// NewState - создание нового State
func NewState() *State {
    return &State{data: make(map[string]interface{})}
}

// Get - получение значения по ключу
func (s *State) Get(key string) interface{} {
    return s.data[key]
}

// Set - установка значения по ключу
func (s *State) Set(key string, value interface{}) {
    s.data[key] = value
}

type Node struct {
    // Name is the unique identifier for the node.
    Name string

    // Function is the function associated with the node.
    // It takes a context and a slice of MessageContent as input and returns a slice of MessageContent and an error.
    Function func(ctx context.Context, state *State) (*State, error)
}

type Edge struct {
    // From is the name of the node from which the edge originates.
    From string

    // To is the name of the node to which the edge points and is generated by the condition function.
    To func(ctx context.Context, state *State) string
}

const END = "END"

var (
	// ErrEntryPointNotSet is returned when the entry point of the graph is not set.
	ErrEntryPointNotSet = errors.New("entry point not set")

	// ErrNodeNotFound is returned when a node is not found in the graph.
	ErrNodeNotFound = errors.New("node not found")

	// ErrNoOutgoingEdge is returned when no outgoing edge is found for a node.
	ErrNoOutgoingEdge = errors.New("no outgoing edge found for node")
)



func NewStateGraph() *StateGraph {
	return &StateGraph{
		nodes: make(map[string]Node),
	}
}

func (g *StateGraph) AddNode(name string, fn func(ctx context.Context, state *State) (*State, error)) {
    g.nodes[name] = Node{
        Name:     name,
        Function: fn,
    }
}

func (g *StateGraph) AddEdge(from, to string) {
    g.edges = append(g.edges, Edge{
        From: from,
        To: func(_ context.Context, state *State) string {
            return to
        },
    })
}

func (g *StateGraph) AddConditionalEdge(from string, condition func(ctx context.Context, state *State) string) {
    g.edges = append(g.edges, Edge{
        From: from,
        To: condition,
    })
}

// SetEntryPoint sets the entry point node name for the state graph.
func (g *StateGraph) SetEntryPoint(name string) {
    g.entryPoint = name
}

// Runnable represents a compiled state graph that can be invoked.
type Runnable struct {
    // graph is the underlying StateGraph object.
    graph *StateGraph
}

// Compile compiles the state graph and returns a Runnable instance.
// It returns an error if the entry point is not set.
func (g *StateGraph) Compile() (*Runnable, error) {
    if g.entryPoint == "" {
        return nil, ErrEntryPointNotSet
    }

    return &Runnable{
        graph: g,
    }, nil
}

// Invoke executes the compiled state graph with the given initial state.
// It returns the resulting state and an error if any occurs during the execution.
func (r *Runnable) Invoke(ctx context.Context, initialState *State) (*State, error) {
    currentNode := r.graph.entryPoint
    state := initialState

    for {
        if currentNode == END {
            break
        }

        node, ok := r.graph.nodes[currentNode]
        if !ok {
            return nil, fmt.Errorf("%w: %s", ErrNodeNotFound, currentNode)
        }

        var err error
        state, err = node.Function(ctx, state)
        if err != nil {
            return nil, fmt.Errorf("error in node %s: %w", currentNode, err)
        }

        foundNext := false
        for _, edge := range r.graph.edges {
            if edge.From == currentNode {
                currentNode = edge.To(ctx, state)
                foundNext = true
                break
            }
        }

        if !foundNext {
            return nil, fmt.Errorf("%w: %s", ErrNoOutgoingEdge, currentNode)
        }
    }

    return state, nil
}

